microsoft/azure-privacy-sandbox-kms

- Makefile
This allows use to use the make target `start-host` while specifying the `--http2` option which lets the KMS work with B&A servers
> Add an extra_args parameter to start-host

- Makefile
- scripts/kms_wait.sh
- Edit scripts/kms_wait.sh so that it respects KMS_URL
- Add CCF_SANDBOX_EXTRA_ARGS to start-host-idp so that it can be used for browser testing
Internal dev repository PR: https://github.com/microsoft/privacy-sandbox-dev/pull/67
> Allow to configure extra sandbox args for start-host-idp

- Makefile
It makes sure that the path is always `test/utils/jwt/nohup.out`. It's not the case in CI at the moment.
The manual says:
```
If standard output is a terminal, append output to
'nohup.out' if possible, '$HOME/nohup.out' otherwise.  If
standard error is a terminal, redirect it to standard output.  To
save output to FILE, use 'nohup COMMAND > FILE'.
NOTE: your shell may have its own version of nohup, which usually
supersedes the version described here.  Please refer to your
shell's documentation for details about the options it supports.
```
https://man7.org/linux/man-pages/man1/nohup.1.html
So it should be safer to specify the nohup.out path explicitly.
It doesn't break the CI in dev repo: https://github.com/microsoft/privacy-sandbox-dev/pull/153/commits/c9782712ddd4a85f2d3c6dbdc52e417bff46 …
> Specify nohup.out path explicitly

- governance/jwt/set_jwt_ms_validation_policy_proposal.json
- scripts/generate_jwt_proposal_payload.sh
- test/utils/jwt/src/index.ts
- Remove ext_expires_in to match managed identity JWT
- Change type of expires_in to match managed identity JWT (The original is correct in terms of RFC as Ronny suggests in https://github.com/microsoft/azure-privacy-sandbox-kms/pull/35#discussion_r1675422972)
Related PR: https://github.com/microsoft/privacy-sandbox-dev/pull/167
> Remove ext_expires_in to match managed identity JWT

- docker/Dockerfile
- Use stable version of CCF
- Add some missing files
- Make consistent interface with privacy-sandbox-dev
- Make rebuilds of snp and virtual KMS's more efficient
> Improve runtime docker image

- docker/Dockerfile
Previous method of copying nvm installation minimised the number of layers in the runtime image to speed up policygen, but it was brittle because the lack of * in ENV required hardcoding the version of node
> Install node in runtime docker file

- app.json
Set forwarding_required in app.json to always. This fixes service not available in mCCF.
> Set forwarding_required in app.json to always

- scripts/add_hostdata_keyreleasepolicy.sh
- test/e2e-test/src/index.ts
The new scripts/add_hostdata_keyreleasepolicy.sh allow us to add hostdata to  the key release policy.
Usage:
scripts/add_hostdata_keyreleasepolicy.sh --network_url $KMS_URL --certificate_dir $KEYS_DIR --hostdata 73973b78d70cc68353426de188db5dfc57e5b766e399935fb73a61127ea26d20
This adds the hostdata in our test attestation to the key release policy
> Add script to add hostdata value to the key release policy

- src/endpoints/refreshEndpoint.ts
- test/e2e-test/src/index.ts
- test/system-test/test_pubkey.py
Make kid change done by @sureshchaha and make sure CI is passing.
OHTTP works with a 2 digit kid. Kid space reduced to 10-99.
> Fix kid bug

- docker/Dockerfile
This change adds logs from the CCF network and KMS to the container logs.
This gives us a better understanding of what the KMS is doing, previously we were only emitting logs from the setup process
> Tail kms logs instead of /dev/null

- .gitignore
- governance/constitution/kms_actions.js
- src/attestation/AttestationValidation.ts
- src/authorization/AuthenticationService.ts
- src/authorization/certs/MemberCertValidator.ts
- src/authorization/certs/UserCertValidator.ts
- src/authorization/jwt/DemoJwtProvider.ts
- src/authorization/jwt/JwtValidationPolicyMap.ts
- src/authorization/jwt/JwtValidator.ts
- src/authorization/jwt/MsJwtProvider.ts
- src/endpoints/keyReleasePolicyEndpoint.ts
- src/endpoints/kms.ts
- src/policies/KeyReleasePolicy.ts
- src/policies/Settings.ts
- src/utils/KmsError.ts
- src/utils/Logger.ts
- src/utils/ServiceRequest.ts
- src/utils/ServiceResult.ts
- src/utils/Tooling.ts
- test/unit-test/policies/Settings.test.ts
- test/unit-test/utils/KmsError.test.ts
- test/unit-test/utils/Logger.test.ts
Extend Logger with LogContext including scope and request id. This allow us to correlate requests with the logs in KMS in order to  debug transactions.
The basis of this development was done by @yf23.
1. Request ID enhancement
- Reads request ID from KMS endpoint requests from the following fields (in order)
```
[
'x-ms-kms-request-id',
'x-ms-request-id',
'x-request-id',
'request-id',
'requestid',
]
```
- Use timestamp as request ID if request does not contain request ID.
- _**Need to improve: I cannot get `uuid` package working. Preferrable to generate random UUID.**_ 
- Returns accepted request ID in response header `x-ms-kms-request-id`
2. Log Enrichment with `LogContext`
Add function scope stack and request ID to KMS log with `LogContext`. The output format is …
> upstream of transparanty kms logger

- .github/workflows/ci.yml
After the e2e tests we print out the CCF log file.
Add a daily schedule to run CI
> print log and add daily schedule for CI

- Makefile
- README.md
- app.json
- scripts/settings-policy-set.sh
- src/endpoints/kms.ts
- src/endpoints/settingsPolicyEndpoint.ts
- src/index.ts
- src/policies/Settings.ts
- src/repositories/Maps.ts
- src/utils/ServiceRequest.ts
- test/e2e-test/src/index.ts
- test/system-test/endpoints.py
- test/system-test/test_settingsPolicy.py
- test/system-test/utils.py
- test/unit-test/policies/Settings.test.ts
There was a bug in retrieving the settings from the KV map which is fixed. As a result the default was always used which resulted in debug log not being logged.
New unit tests and pytest added
Added unit tests command to makefile
> Bugfix - Retrieve Settings from KV map

- .github/workflows/endpoint-test.yml
- scripts/ccf/az-cleanroom-aci/down.sh
- scripts/ccf/az-cleanroom-aci/up.sh
This is currently blocked on https://github.com/Azure/azure-cleanroom/pull/12 so raising as a separate PR
> Run `az-cleanroom-aci` tests in parallel

- .github/workflows/cleanup.yml
- .github/workflows/endpoint-test.yml
- .github/workflows/system-tests.yml
- scripts/akv/down.sh
- scripts/akv/key-import.sh
- scripts/akv/up.sh
- scripts/ccf/az-cleanroom-aci/down.sh
- scripts/ccf/member/add.sh
- scripts/ccf/propose.sh
- scripts/kms/constitution_set.sh
- test/system-test/conftest.py
- test/system-test/endpoints.py
- test/system-test/test_key.py
In order to test azure-cleanroom based CCF networks, we want to have testing with as representative systems as possible. Production systems will store member identities in something like AKV rather than locally, so we want test coverage of this
> Add AKV support to system tests

- test/e2e-test/src/index.ts
I've noticed some occurrences of e2e CI getting timed out in fetching the key.
Improved the loop waiting for 200 after 202 to prevent an infinite loop.
> Fix waiting for 200 loop. Could cause infinitive loop

- scripts/ccf/az-cleanroom-aci/up.sh
`az-cleanroom-aci/up.sh` globally trusts the CCF networks service certificate as pointed out in the review of #259. 
This means we wouldn't need to provide the service cert to our HTTP requests, however if a CCF network was deployed separately, it's simpler to just provide the service cert rather than updating the system to globally trust it. Global trusting also provides the opportunity to step on existing certs breaking requests to that service.
For those reasons I think it's better to explicitly state the service cert in each request, making globally trusting it here redundant.
> Remove globally trusting az cleanroom cert

- .github/workflows/system-test.yml
Looks like the CI fails consistently since using ubuntu 24.04, so rolling back to 22.04 to see if it improves things
> Roll back to ubuntu 22.04

- .github/workflows/ci.yml
- .github/workflows/system-test.yml
- scripts/ccf/az-cleanroom-aci/up.sh
The up.sh script is set to fail fast which means the retry mechanism won't behave as expected
We also don't check that the az cli command fully completes which can lead to a network being up, but not fully configured
> Fix retry mechanism in az cleanroom CCF network up

- .github/workflows/ci.yml
- package.json
The errors we see intermittently in the e2e tests have this message
```
Error: or [Error]: Unknown file extension ".ts" for /workspaces/azure-privacy-sandbox-kms/test/e2e-test/src/index.ts
```
It appears that the current method of running typescript files directly with node is very error prone, so using ts-node instead
> Use ts-node to run e2e tests

- .github/workflows/system-tests.yml
- .gitignore
- Makefile
- README.md
- scripts/generate_access_token.sh
- scripts/jwt_issuer/down.sh
- scripts/jwt_issuer/up.sh
- services/docker-compose.yml
- test/system-test/conftest.py
- test/utils/jwt/src/index.ts
If we want to run multiple concurrent JWT issuers for testing in #260 we need to be able to have separate instances of the test JWT issuer run at once
> Allow running concurrent JWT issuers

- docker/Dockerfile
- services/docker-compose.yml
- test/utils/jwt/src/index.ts
Since #266, the test JWT issuer doesn't use a fixed port, privacy-sandbox-dev assumes it does which breaks it's testing.
To fix this the options are to either:
- Allow setting the port of the JWT issuer to the port assumed by privacy-sandbox-dev
- Read the full address in privacy-sandbox-dev
Since privacy-sandbox-dev assumes the port in many places (including in an instance running in ACI) it's non-trivial to do the first change, so opting for the latter.
> Allow setting of JWT Issuer port

- .github/workflows/system-test.yml
- scripts/tools/install-deps.sh
To handle issue https://github.com/microsoft/azure-privacy-sandbox-kms/issues/278.
The problem reproduces in local containers too not only in github actions runner. ubuntu 24.04 struggles to run `pip install` even locally (it took around 10 minutes while it's 1 min with 20.04). It seems to be panda library which is especially slow.
The error in the CI is just token expiration, so I moved the login step just before it's required.
> Use ubuntu 24.04 (latest) for system-test CI

- services/ccf-sandbox/Dockerfile
- services/ccf-sandbox/docker-compose.yml
- services/docker-compose.yml
The CCF containers use the latest version and  an update this week broke our CCF. This fixes the versions for the containers used in our containers
> Force CCF container base image versions

- app.json
The redirects reveal the URL to the KMS endpoints and should not leak to the clients.
We stop redirecting for read-only endpoints to prevent the redirection strategy from revealing the URL to the KMS endpoints..
> stop redirecting for read only endpoints

- .github/workflows/system-test.yml
- test/system-test/conftest.py
- test/system-test/test_all_seq.py
We decided that the current test strategy for Azure based KMS testing was too expensive, particularly in the peak usage of ACI (and eventually ACL). 
This is because each individual test currently spins up it's own fresh KMS instance (and therefore a fresh Azure resource/s) in order to keep each test isolated from the side effects of other tests.
There are two potential solutions to the high peak usage. 
- Run the existing tests in sequence
- However this doesn't reduce total usage
- Perhaps more crucially, since deploying machines in Azure takes a lot of time, doing so sequentially for each test would make the total test time prohibitively long
- Write a new test which only needs one KMS instance
- This gives up test isolation, but reduces the peak usage of Azure services.
We decided to …
> Add a set of tests which are run on single KMS instance

- .github/workflows/system-test.yml
Running several PRs, far too long (~10 mins) is spent installing dependencies which are likely unnecessary. #294 Attempts to solve this problem, however some of the older tests fail.
This PR removes the unnecessary dependencies for the system tests. **This speeds up the install deps step from ~10 minutes to ~10 seconds, for simple tests that takes total time from 12 minutes to 2 minutes**
> Speed up system test dependency install

- .github/workflows/cleanup.yml
- .github/workflows/system-test.yml
- .github/workflows/test-orchestrator.yml
- services/cacitesting.env
The exception to deploy storage accounts with shared key authentication (which is a requirement for deployment a az cleanroom CCF network) is now active. This means we can deploy everything on our DEV AND TEST subscription instead of using the parakeet subscription.
> Return to using the DEV AND TEST subscription

- .github/workflows/daily.yml
- .github/workflows/system-tests.yml
- test/system-test/test_constitution.py
- test/system-test/test_governance.py
- test/system-test/test_key.py
- test/system-test/test_keyReleasePolicy.py
- test/system-test/test_keyRotationPolicy.py
- test/system-test/test_operations.py
- test/system-test/test_settingsPolicy.py
- test/system-test/test_unwrapkey.py
In #323, I forgot to run `daily.yml` which exposed two issues
- I wasn't properly setting the `parallel` field to make stateless ACL tests run sequentially.
- I haven't marked expected failures (due to lack of governance application endpoints) in the normal stateless tests
> Mark expected failures in stateless tests on ACL

- scripts/ccf/acl/down.sh
When running ACL tests sequentially, we run into a problem where the ACL is still being deleted when we start the next test because of the `--no-wait` flag, so we don't want to include it in this case. 
Since we still want it sometimes to speed things up, we can still optionally include it
> Don't assume no-wait on ACL down

- .github/workflows/cleanup.yml
- scripts/tools/cleanup_resource_group.sh
I noticed after adding ACL support I forgot to add cleanup code to handle ACL instances. This led me to decide that a better system uses an allowlist of specific resources to keep and just deleting everything else.
This trades the chance to forget to add a persistent resource to the allow list and accidentally delete it for not needing to explicitly handle new resource types when added
> Refactor cleanup workflow to allowlist structure

- test/system-test/conftest.py
Sometimes `daily.yml` fails because we attempt to start new ACL instances while the old one is still "in" the system. This is because we re-use the deployment name from the last run.
> Ensure down in conftest.py unsets env variables

- requirements.txt
We don't use it and installing it takes 10 minutes on all of our tests
- Unit tests go from 9m to 40s
- e2e tests go from 27m to 10m
> Remove pandas dependency in requirements.txt

- .github/workflows/daily.yml
We have a feature branch for the work to move governance to application endpoints. In order to have proper test coverage, we should run `daily.yml` on pushes to that branch
> Run the daily workflow on feature branches

- Makefile
- scripts/kms/endpoints/auth.sh
- test/system-test/conftest.py
- test/system-test/endpoints.py
- test/system-test/test_all_seq.py
- test/system-test/test_auth.py
This is useful in particular for testing the change for moving JWT issuer trust from governance to application code
> Add tests for the `/auth` endpoint

- .github/workflows/ci.yml
- .github/workflows/daily.yml
In order to get all of the features we needed, we install a custom build of the cleanroom extension in `scripts/ccf/az-cleanroom-aci/setup.sh`
However since this version doesn't get changes, we are now sufficiently stale that attestation validation fails (some expected version has moved on)
Since we're likely to move to ACL, it's only worth attempting to fix if it's cheap, however after spending some time doing a fresh build of the extension and the container image we previously had custom builds of it doesn't work.
Therefore I think the pragmatic thing for now is to disable this testing but keep the code. If we move back to cleanroom the code is still there and we just need to investigate and fix the custom builds mechanism. If we complete the move to ACL we can delete the az cleanroom …
> Disable testing on az cleanroom based KMS

- requirements.txt
Privacy-sandbox-dev CI has been failing to build KMS. The logs claim it can't find the required version of pre-commit and matplotlib.
Quick solution is revert those bumps, I will also follow up with tests for building in the same way as privacy-sandbox-dev, and maybe investigating why it fails there and not here
> Revert version bumps

- .devcontainer/install_packages.sh
- docker/Dockerfile
- docker/run_kms_standalone.sh
The existing standalone image for KMS (which is a single docker image which can run CCF and puts the KMS on top) is very complex and is currently failing.
> Fix the standalone image used for testing privacy-sandbox

- .github/workflows/ci.yml
- docker/docker-compose.yml
For testing privacy sandbox, we want a single image which runs the KMS on top of a local CCF (so the CCF sandbox is sufficient). It will save us some time to test building this image on PRs
> Add a test for the standalone KMS image

- docker/Dockerfile
- docker/run_standalone_kms.sh
If the runtime CMD for the standalone KMS image is a script, we can iterate on it to fix dependabot issues without having to modify privacy sandbox dev code
- CI Run: https://github.com/microsoft/privacy-sandbox-dev/actions/runs/13787080470
> Move KMS standalone image CMD into a script

- docker/run_standalone_kms.sh
Simplifies the KMS standalone image, it looks like we use AAD for privacy-sandbox-dev so this isn't needed
> Don't run the dummy JWT issuer in standalone KMS image

- docker/run_standalone_kms.sh
We build the KMS in a previous step and copy it over
> Don't build the KMS in the runtime image

- test/system-test/test_settingsPolicy.py
We run extra testing in the daily set of tests and last night it caught that a test was fixed by #377 on ACL
> Remove expected failure on ACL

- test/system-test/test_unwrapkey.py
While testing ACL based KMS's, Slava was led to believe by our tests for `/unwrapKey` that setting the settings policy is required for the endpoint to work, which it isn't. 
This lost him time and makes the tests expand their coverage outside of their intended domain unnecessarily, it would be confusing if these tests failed because setting the settings policy had a bug.
Remove the calls to `set_settings_policy.sh`
> Remove redundant settings policy setting

- scripts/ccf/acl/up.sh
If the user wants to hook into an already running ACL based KMS, perhaps in a second terminal, they have to manually export all the env variables which `up.sh` exports.
The other `up.sh` scripts also have the behaviour that running again with the same service described just confirms they're running and exports the environment for you, `acl/up.sh` should match this behaviour
> Allow acl/up.sh to be called repeatedly without recreating the ACL

- scripts/kms/endpoints/unwrapKey.sh
- test/system-test/test_all_seq.py
- test/system-test/test_keyRotationPolicy.py
- test/system-test/test_unwrapkey.py
- test/system-test/utils.py
We noticed calling unwrapKey.sh from bash was returning 400. After investigation this turned out to be because bash command substitution removed the trailing newline from the wrappingKey. This didn't happen in tests because we weren't executing in a shell and any other caller is just making the raw HTTP request
I've only made the testing change for unwrap key to speed things up but we should do the same for the other endpoints. It is better to see the exact bash being called for reproducability
> Fix calling unwrapKey.sh from bash

- scripts/kms/endpoints/key.sh
- scripts/kms/endpoints/keyReleasePolicy.sh
- scripts/kms/endpoints/settingsPolicy.sh
- scripts/kms/endpoints/unwrapKey.sh
- test/system-test/conftest.py
- test/system-test/test_all_seq.py
When we support ACL with no local certs, this means many tests which rely on local certs will break. Those tests aren't specifically testing local certs so we can just default our authentication policy to JWT to avert this issue
> Default to JWT auth in testing

- services/ccf-sandbox/Dockerfile
Refactoring privacy-sandbox-dev means we can reuse the CCF image, this means we can make the performance optimisation to include SNP builds
> Speed up start time for all ccf sandbox images

- docker/run_standalone_kms.sh
To facilitate using confidential ledger scoped token in privacy-sandbox-dev, we must configure the KMS to expect the v2 token
> Expect a v2 MI token in standalone image

- test/system-test/test_proposals.py
After merging #457 I noticed that sometimes in CI we can get two events by chance which in combination cause `test_proposals.py` to fail.
- In `test_proposals_multiple` the test proposal to set the key release policy can sometimes happen on the same timestamp second as the setup proposal to configure the JWT issuer
- If the timestamps are the same, there is then no way to distinguish the order of the proposals, so the proposal actions are in a non-deterministic order
When both these things happen, the test fails. I noticed the same issue with `test_proposals_caps_to_five` since that submits proposals in a loop and therefore submits them fast enough to always hit point 1 and has a sufficiently large number of proposals to make point 2 almost always happen.
The solution to both is to sleep …
> Ensure proposal timestamps are distinct in tests
